spring:
  application:
    name: demo
  datasource:
    url: jdbc:mysql://localhost:8082/rabc?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver